"""
Placement results. Bhava phala and rasi phala for the grahas themselves.

This is a different question from the one `interpret.LORD_IN_HOUSE` answers.
That corpus reads a graha as the ruler of a house it may be nowhere near. This
one reads the graha where it actually sits: what Saturn in the 7th does, what
Mars in Cancer does, regardless of what either of them rules.

A full reading uses both. A graha carries its lordships into the house it
occupies, and the occupation has its own result on top.

Sources: the bhava phala chapters of BPHS, Phaladeepika chapters 10 to 15,
and Saravali for the sign material.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Graha in sign. How the sign conditions the graha's method and tempo.
# ---------------------------------------------------------------------------

GRAHA_IN_SIGN = {
    "Sun": {
        0: "Exalted. Command comes naturally and early. Pioneering, hot tempered, unwilling to take a second seat, and inclined to burn through people who slow it down.",
        1: "Pride attaches to what is owned and enjoyed. Steady, immovable sense of self, slow to concede a point, and status expressed through possessions rather than rank.",
        2: "Identity is built out of intelligence and speech. Many interests, articulate authority, and a self that is genuinely plural rather than merely versatile.",
        3: "Authority exercised through care and protection. The father is emotionally significant or emotionally absent, and pride is unusually easy to wound.",
        4: "Own sign. Full self-possession. Natural command, generosity from a position of strength, and a real need to preside over something.",
        5: "Authority through precision and usefulness. Self-worth is tied to being correct, which makes for excellent work and a harsh internal critic.",
        6: "Debilitated. The self is handed to other people to define. Strong need for approval, identity found through partnership, and a father who was diminished or distant.",
        7: "Power kept out of sight. Strategic, penetrating, unwilling to reveal its hand, and drawn to whatever is hidden from ordinary view.",
        8: "Authority that rests on principle. Teacherly, morally certain, and genuinely uninterested in power that cannot be justified.",
        9: "Authority earned rather than assumed. Austere, patient, willing to wait years for standing, and dismissive of anything handed over.",
        10: "Authority located in the group rather than the person. Unorthodox, egalitarian by instinct, and usually at some distance from the father.",
        11: "The self dissolves into something larger. Compassionate, poorly defined at the edges, and more comfortable serving than leading.",
    },
    "Moon": {
        0: "The mind moves first and thinks after. Quick reactions, short fuse, emotional courage, and impatience with anything slow.",
        1: "Exalted. The steadiest mind available. Hard to disturb, comforted by the senses, and reluctant to change an emotional position once taken.",
        2: "A plural mind that thinks by talking. Processes feeling as information, changes register quickly, and needs conversation the way others need rest.",
        3: "Own sign. Deep feeling, strong maternal bond, tidal moods. The emotional life is the real life, and everything else is arranged around it.",
        4: "A proud mind that needs an audience. Warm, generous, dramatic in feeling, and genuinely hurt by being overlooked.",
        5: "An analytical mind whose resting state is worry. Notices every flaw including its own, and manages anxiety through routine and health.",
        6: "A relational mind. Decides by weighing, needs harmony to function, and can lose track of its own preference inside someone else's.",
        7: "Debilitated. Feeling runs deep and stays buried. Intense, mistrustful, slow to open, and carrying more than it shows. Emotional recovery is slow but complete.",
        8: "An optimistic mind that needs meaning more than comfort. Restless for distance, philosophical about setbacks, poor at sitting still.",
        9: "Feeling is contained and put to work. Mature early, duty before comfort, and often a mother who was more responsible than warm.",
        10: "A detached mind. Humane in the abstract, distant in the particular, and unconventional in what it needs to feel settled.",
        11: "A porous mind that absorbs whatever is around it. Imaginative, compassionate, easily flooded, and needing deliberate solitude to stay clear.",
    },
    "Mars": {
        0: "Own sign. Direct action without a preliminary. Competitive, first to move, and better at starting than finishing.",
        1: "Slow to rouse and immovable once roused. Fights over resources and territory rather than ideas, and holds a grievance for years.",
        2: "Energy expressed through speech and the hands. Skilled, argumentative, technically able, and scattered across too many fronts.",
        3: "Debilitated. Force turns inward and sideways. Passive aggression, energy tied up in home and family, and anger that leaks rather than lands.",
        4: "Proud force, exercised openly. Commanding, dramatic in anger, generous afterwards, and unable to operate under someone else's authority.",
        5: "Precise, technical energy. Excellent with instruments and systems, critical edge, and a tendency to attack detail rather than the actual problem.",
        6: "Fights through negotiation and alliance. Energy is spent in partnership, which makes for good advocacy and difficult marriages.",
        7: "Own sign. Strategic, patient, relentless. Does not announce the attack, does not forget, and works best where the stakes are hidden.",
        8: "Crusading energy. Fights for a principle rather than an interest, which makes it effective and occasionally insufferable.",
        9: "Exalted. Disciplined force, the best executive placement available. Ambition with the patience to execute, and coldness under pressure.",
        10: "Energy spent on the collective. Rebellious, reform-minded, and uninterested in fighting for personal advantage.",
        11: "Diffuse energy driven by feeling. Acts when moved and stalls when not, which reads as inconsistency to everyone watching.",
    },
    "Mercury": {
        0: "Fast, blunt speech. Reaches a conclusion before finishing the analysis, and defends it afterwards.",
        1: "Slow, deliberate, practical thought. Once an opinion is formed it is structural. Good with money, poor at revision.",
        2: "Own sign. Quick plural intelligence and genuine restlessness. Learns fast, tires fast, and needs several subjects running at once.",
        3: "Reasoning through memory and feeling. Indirect speech, excellent recall, and arguments that are really about something else.",
        4: "Authoritative speech. Speaks in conclusions, dislikes correction, and is more persuasive than precise.",
        5: "Exalted and in moolatrikona. The sharpest analytical placement there is. Discriminating, editorial, and inclined to mistake precision for judgement.",
        6: "Diplomatic speech that weighs both sides. Fair, persuasive, and capable of genuine indecision at the point of choosing.",
        7: "An investigative mind. Secretive, research-minded, sharp tongued when provoked, and comfortable with what other people will not look at.",
        8: "Debilitated. Sees the whole and loses the parts. Broad, sincere, preachy, and unreliable on detail. Better at teaching than at accounting.",
        9: "Structured practical thought. Conservative, methodical, and interested in what actually works rather than what is clever.",
        10: "Inventive systems thinking. Contrarian by reflex, ahead of the room, and impatient with received procedure.",
        11: "Intuition running ahead of logic. Poetic, vague, occasionally exact in ways it cannot explain. Written expression outperforms spoken.",
    },
    "Jupiter": {
        0: "Faith with a crusading edge. Expansive courage, strong convictions, and impatience with slow institutions.",
        1: "Expands wealth and comfort. Values-driven counsel, generous in material terms, and attached to the good life it recommends against.",
        2: "Debilitated. Information mistaken for knowledge. Widely read, scattered, and better at gathering positions than holding one.",
        3: "Exalted. The best placement Jupiter has. Nourishing, protective wisdom, sound judgement, and counsel people actually take.",
        4: "Authoritative teaching. Generous, proud, and inclined to advise from a throne rather than beside the person.",
        5: "Wisdom through detail and service. A critical faith that improves things rather than blessing them. Undervalues its own expansiveness.",
        6: "Fair judgement, expansion through partnership. Good arbitration, and a tendency to defer where it should decide.",
        7: "Occult and research wisdom. Faith arrived at through crisis rather than instruction, and a real appetite for the hidden.",
        8: "Own sign and moolatrikona. The natural teacher. Philosophical, principled, expansive, and genuinely persuasive about meaning.",
        9: "Debilitated. Faith becomes pragmatism. Expansion is delayed, optimism is rationed, and belief has to survive a long dry stretch before it holds.",
        10: "Humanitarian wisdom, unorthodox belief. Serves the many, distrusts hierarchy, and is often ahead of its own tradition.",
        11: "Own sign. Devotional and compassionate. Boundless generosity, weak boundaries, and mysticism that is genuine rather than decorative.",
    },
    "Venus": {
        0: "Impulsive attraction. Fast to want, fast to move, competitive in love, and bored by the settled version.",
        1: "Own sign. Sensual, steady, loyal affection. Loves comfort and beauty in physical form, and is slow to leave anything it has invested in.",
        2: "Plural attraction and verbal romance. Flirtatious, charming, and needing conversation more than depth to stay interested.",
        3: "Love as nurture. Home-centred affection, strong emotional attachment, and a partner who is also a family member in feeling.",
        4: "Proud, generous, dramatic love. Wants to be adored openly and gives lavishly in return.",
        5: "Debilitated. Love expressed as service and correction. Modest, useful, critical of the beloved, and uneasy with being simply enjoyed.",
        6: "Own sign and moolatrikona. Refined, diplomatic, aesthetic. The most natural placement for partnership and for taste.",
        7: "Intense, possessive desire. Transformative attachments, jealousy, and love that operates at the level of consequence rather than pleasure.",
        8: "Philosophical love that needs freedom. Drawn to the foreign and the far, and uncomfortable with anything that closes the exits.",
        9: "Pragmatic love. Often an older, more serious or more established partner, and affection that shows as reliability rather than warmth.",
        10: "Unconventional relationships and detached affection. Loves the person as an idea, and needs the arrangement to be unusual to stay interested.",
        11: "Exalted. Devotional, boundless, self-sacrificing love. The most refined placement, and the one most likely to give away more than it has.",
    },
    "Saturn": {
        0: "Debilitated. Discipline without patience. Frustrated drive, anger at limits, and a long argument with authority that is really an argument with time.",
        1: "Patient accumulation. Slow, durable wealth, endurance in material matters, and immovability once committed.",
        2: "Disciplined communication. Dry, exact, structured learning, and speech that is spare to the point of being read as cold.",
        3: "Emotional restriction. Duty placed above feeling, a mother who was dutiful rather than warm, and comfort that has to be earned.",
        4: "Restricted authority. Pride is repeatedly checked, recognition arrives late, and the ego is disciplined whether or not it consents.",
        5: "Methodical labour. Perfectionist service, chronic overwork, and health that reports the overwork before the mind does.",
        6: "Exalted. Saturn at its best: justice, fairness, mature partnership, and the patience to build something that outlasts the builder.",
        7: "Endurance through crisis. Deep chronic patterns, survival capacity, and a refusal to be finished off by anything.",
        8: "Disciplined belief. Conservative philosophy, respect for lineage, and a faith that is structural rather than felt.",
        9: "Own sign and moolatrikona. Structural mastery. Ambition, austerity, and the ability to build institutions that hold.",
        10: "Own sign. Systemic reform and detached service. Works for the collective, keeps its distance from individuals.",
        11: "Duty inside dissolution. Spiritual discipline, isolation as a working condition, and service given where no credit returns.",
    },
    "Rahu": {
        0: "Reckless drive and an obsession with being first. Enormous initiative, poor judgement about when to stop.",
        1: "Hunger for wealth and sensation that does not switch off once fed. Accumulates, and stays hungry.",
        2: "Obsession with information and many voices at once. Persuasive to the point of manipulation, and rarely still.",
        3: "Unstable emotional hunger. Foreign home or foreign mother, and a nourishment that never quite arrives.",
        4: "An obsessive need for recognition. Capable of enormous visibility and unable to be satisfied by it.",
        5: "Obsessive analysis and health anxiety. Genuinely skilled with systems, and inclined to disappear into them.",
        6: "Obsessive relating. Unconventional partnerships, and a hunger to be chosen that distorts the choosing.",
        7: "Occult obsession and a hunger for hidden power. Real depth here, and real danger of going under.",
        8: "Dogmatic belief and guru fixation. Adopts a system wholesale and defends it past the point of usefulness.",
        9: "Relentless ambition, and one of the two signs where Rahu functions cleanly. Climbs, and the climbing works.",
        10: "Technological and collective obsession. The other placement where Rahu works: unorthodox methods that turn out to be correct.",
        11: "Escapism and mystical confusion. Genuine spiritual reach mixed with a real risk of substances and self-deception.",
    },
    "Ketu": {
        0: "Detached from self-assertion. Acts in sudden bursts, then loses interest in the outcome.",
        1: "Indifferent to wealth and comfort while remaining perfectly capable of producing both.",
        2: "Detached from ordinary chatter. Speaks little, cryptically, and often to the point.",
        3: "Cut off from the nourishing line. Mother, home and belonging feel provisional, which drives the search elsewhere.",
        4: "No appetite for recognition despite the capacity for it. Refuses the stage it could easily hold.",
        5: "Mastery of detail with no interest in applying it. Precision that will not be monetised.",
        6: "Withdrawal from partnership. Capable of deep relating, unwilling to be held by it.",
        7: "The natural occultist. Real depth, past mastery, and a pull toward what cannot be verified.",
        8: "The inner guru. Rejects external teachers, sometimes correctly and sometimes at real cost.",
        9: "Detached from ambition. Can build, will not campaign, and quietly outlasts those who do.",
        10: "Detached from groups. Solitary even inside the collective it serves.",
        11: "The strongest placement for moksha. Natural renunciate, dissolved boundaries, and little grip on the material.",
    },
}

# ---------------------------------------------------------------------------
# Graha in house. What the occupation itself does, independent of lordship.
# ---------------------------------------------------------------------------

GRAHA_IN_HOUSE = {
    "Sun": {
        1: "The self is lit from within. Strong constitution, upright bearing, and a presence people register before you speak. Also pride, a hot constitution, and a tendency to be the last to notice you are dominating a room. The father shapes the identity heavily, present or absent.",
        2: "Wealth through authority, government or your own name. Speech carries weight and can carry heat. Family pride is real and occasionally expensive. Classical texts flag the eyes and the teeth here.",
        3: "Courage as a standing resource. Self-driven, willing to act alone, effective with the hands. Younger siblings are few, or strong-willed, or both. Nothing much is delegated.",
        4: "Restlessness on home ground. Property and vehicles come through position rather than inheritance. The mother's matters carry weight, and the classical caution is the heart and the chest.",
        5: "Intelligence used to command. Authority through creative or advisory work. Children are few or arrive late, and speculation is a losing habit here rather than a winning one.",
        6: "Enemies do not prosper. Strong competitive and diagnostic instinct, well suited to medicine, law, audit and the services. Digestion and the stomach are the standing health note.",
        7: "The partner is a strong personality, or the marriage is where the ego gets its education. Delays are common. Business with institutions and government works well.",
        8: "Longevity is generally good, and reached through tests rather than around them. Genuine occult aptitude. The father's health is a recurring theme, and inheritance is entangled.",
        9: "Fortunate and dharmic. The father is prominent and formative. Authority through teaching, law or religion, and long journeys that change the life's direction.",
        10: "Full directional strength. The strongest placement the Sun has. Career authority, public standing, government or executive work, and a reputation that arrives ahead of you.",
        11: "Substantial gains and powerful friends. Ambitions are met, elder siblings are influential or difficult, and the network is the delivery mechanism.",
        12: "The self is spent out of sight. Foreign residence, institutional work, hospitals or retreat. Status is not the point here, and pursuing it costs. The father is distant. Eyes are the classical caution.",
    },
    "Moon": {
        1: "The mind is worn on the outside. Emotionally readable, changeable, sensitive to atmosphere, and often good-looking in a soft rather than sharp way. The mother is written into the personality.",
        2: "Money and mood move together. Earnings fluctuate, speech is warm and persuasive, and the family of origin stays emotionally central. Food matters more than it does for most.",
        3: "Emotional courage. Frequent short travel, close but changeable sibling bonds, and a mind that steadies itself by staying in motion.",
        4: "The best house for the Moon. Genuine inner peace, a strong mother, property and comfort that actually feel comfortable. Full directional strength.",
        5: "The mind is creative and the creativity is emotional. Strong bond with children, good for teaching and performance, and romance taken seriously.",
        6: "The mind is put under load. Anxiety, digestive and immune sensitivity, and emotional energy spent on work and conflict. Good for healing professions, hard on the person.",
        7: "The partner is emotionally central and the mood of the marriage sets the mood of the life. Popular publicly. Marriage often to someone caring or maternal.",
        8: "Deep, unquiet feeling. Occult and psychological aptitude, real intuition, and emotional patterns that surface in crisis. Emotional privacy is not optional here.",
        9: "Faith is felt rather than argued. A supportive mother and a fortunate life, long journeys taken for the feel of them, and beliefs that carry emotional weight.",
        10: "Public work and a public face. Career touches the many: hospitality, health, media, food, the public. Reputation moves with mood.",
        11: "Gains through people. Large network, income through the public, and friendships that function as family.",
        12: "The mind withdraws. Foreign lands, retreat, hospitals, sleep and the inner life. Strong meditative capacity and a real need for solitude that others read as absence.",
    },
    "Mars": {
        1: "Physical force in the constitution. Strong, quick, scarred, competitive, and visibly impatient. Anger arrives fast and leaves fast. Classical Kuja dosha position for marriage timing.",
        2: "Sharp speech that cuts before it decides to. Money earned through effort and defended aggressively. Family friction over resources.",
        3: "The best house for Mars. Courage, skill and self-effort compound. Brothers are strong or contentious. Excellent for anything that needs nerve.",
        4: "Friction on home ground. Property acquired and fought over, restlessness at home, and the mother's matters carrying heat. Land and vehicles feature.",
        5: "Sharp intelligence with an aggressive edge. Good for strategy, surgery, engineering and competitive sport. Speculation is dangerous. Children's matters carry intensity.",
        6: "Excellent placement. Enemies are defeated, competition is welcome, and the work suits medicine, military, law or engineering. Accidents and inflammation are the health note.",
        7: "Heat in partnership. The marriage runs hot, needs room, and does badly with confinement. Business partnerships need written terms. Kuja dosha position.",
        8: "Sudden events, surgery, and genuine research capacity. Good for insurance, forensics and anything investigative. Accidents are the standing caution.",
        9: "Fights for principle. Strong convictions, contention with the father or with teachers, and long journeys undertaken with force.",
        10: "Full directional strength. Executive drive, technical or military career, and a reputation for getting things done rather than for being pleasant.",
        11: "Gains through effort and competition. Ambitious, well connected in practical circles, and elder siblings who are forceful.",
        12: "Energy spent out of sight. Work in institutions, hospitals or abroad, hidden enemies, and anger that turns inward when it has nowhere to go.",
    },
    "Mercury": {
        1: "Intelligence as the visible trait. Youthful appearance, quick speech, restless hands, and a mind that is always partly elsewhere. Full directional strength.",
        2: "The classical placement for speech and money together. Earns through words, trade or analysis. Persuasive, and occasionally too clever with the truth.",
        3: "Skill and communication combine. Writing, media, negotiation, and dexterity. Younger siblings and short travel feature heavily.",
        4: "The mind is at home. Education completed comfortably, property through trade, and a mother who is intellectually formative.",
        5: "Analytical intelligence applied to creation. Excellent for teaching, writing, mathematics and advisory work. Speculation is tempting and works only when disciplined.",
        6: "The mind solves problems for a living. Excellent diagnostic and administrative capacity. Nervous system and skin are the health note, and worry is the occupational hazard.",
        7: "Partnership with someone younger, quicker or more verbal. Good for business partnerships and trade. The marriage runs on conversation.",
        8: "Investigative intelligence. Research, occult study, psychology and forensics. The mind is drawn to what is concealed, and keeps its own counsel.",
        9: "Higher learning, publishing, law. Belief examined rather than inherited, and long journeys undertaken to learn something specific.",
        10: "Career through intellect, communication or commerce. Full directional strength. Reputation for competence rather than charisma.",
        11: "Gains through networks, trade and information. Wide circle, many acquaintances, and income from more than one source.",
        12: "The mind works in private. Research, writing, translation and foreign work. Speech is guarded, and thinking happens before dawn or after everyone leaves.",
    },
    "Jupiter": {
        1: "The best house for Jupiter. Wisdom in the constitution, respected, generally believed, physically expansive with age. Full directional strength, and its aspect protects the 5th, 7th and 9th at once.",
        2: "Wealth and good speech. Family fortune, generous provision, and a voice people trust. Weight is the standing physical note.",
        3: "Wisdom applied to effort. Publishing, teaching, and siblings who are supportive. Jupiter is mildly uncomfortable here: expansion into a house of initiative dilutes both.",
        4: "Deep contentment. A cultured home, an educated mother, property that carries meaning, and genuine peace of mind. Among the finest placements in the chart.",
        5: "Excellent. Intelligence, children, teaching and past merit all reinforce each other. Advice given here carries weight. Mantra practice actually works.",
        6: "Jupiter is spent on difficulty. Good for medicine, law and service, and a real protector in illness and litigation. But expansion in a house of loss also expands the loss. Liver and weight are the health note.",
        7: "The classical placement for a good spouse: a partner who is a teacher in some sense. Marriage improves the life materially and morally.",
        8: "Longevity and occult wisdom. Inheritance is likely and arrives through complication. Faith is remade by crisis rather than instruction.",
        9: "The strongest house for fortune. A real teacher, a formative father, principled authority, and luck that behaves like grace rather than chance.",
        10: "Career with a moral dimension: law, teaching, religion, policy, counsel. Respected publicly. The reputation outlives the role.",
        11: "Large gains and influential friends. Ambitions are met generously, and the network includes people who open doors on principle.",
        12: "Expenditure on good things: charity, pilgrimage, teachers, foreign study. The classical placement for moksha. Poor at accumulation, excellent at release.",
    },
    "Venus": {
        1: "Beauty and charm in the constitution. Attractive, diplomatic, comfort-seeking, and better at being wanted than at wanting. Vanity is the standing risk.",
        2: "Wealth, good food, and a pleasing voice. Family is refined or well provided for. Money arrives through taste rather than force.",
        3: "Artistic skill and pleasant communication. Siblings are supportive, short travel is enjoyable, and effort is made attractive rather than strenuous.",
        4: "Full directional strength. A beautiful home, vehicles, comfort, and a warm mother. One of the plainest happy placements there is.",
        5: "Romance, creativity and children all lit at once. Excellent for the arts and for teaching them. Love affairs are formative.",
        6: "Venus is compromised here. Pleasure entangled with obligation, difficulty in relationships through work or health, and a tendency to over-give in service. Kidneys and reproductive health are the classical note.",
        7: "The natural house of Venus and the natural karaka of marriage in it. Strong partnership drive, attractive spouse, and a life organised around the pair.",
        8: "Intense, secretive attachments. Gains through the spouse or through inheritance. Desire and transformation are entangled, which is either depth or trouble depending on the rest of the chart.",
        9: "Love of philosophy, travel and the foreign. Often a partner from another culture. Fortune arrives with grace attached.",
        10: "Career in art, design, luxury, diplomacy or entertainment. Publicly liked. The work is pleasant and the standing is real.",
        11: "Gains through art, women, luxury and social connection. Wide, pleasant network and income that arrives without much strain.",
        12: "The classical placement for bed pleasures and for the dissolution of desire, which is the same house doing both. Foreign partners, private indulgence, and, in a spiritual chart, genuine surrender.",
    },
    "Saturn": {
        1: "Restriction written into the body. Serious from childhood, lean or heavy but rarely in between, slow to mature and long-lived. Life begins properly after thirty. Saturn is uncomfortable here and the discipline is not optional.",
        2: "Money is slow and then permanent. Speech is spare, measured and occasionally read as cold. Family of origin was materially or emotionally frugal.",
        3: "The best house for Saturn along with the 6th, 10th and 11th. Effort compounds, discipline is a genuine asset, and siblings are either absent or distant. Long-term projects finish.",
        4: "The hardest placement for peace of mind. Home is a duty before it is a comfort, the mother is dutiful rather than warm, and property arrives late and stays. Real depth underneath it.",
        5: "Children and creativity are delayed or restricted, then durable. Serious intelligence, poor at speculation, and a mind that works best on long problems.",
        6: "Excellent. Enemies fail against endurance, chronic illness is survived, debts are worked off. Well suited to labour, service, law and anything requiring patience against opposition.",
        7: "Full directional strength, and simultaneously the classic marriage delay. The partner is older, more serious, or arrives late. Once formed the union is durable. Business partnerships work.",
        8: "Long life. Chronic patterns, slow-moving crises, and genuine capacity for research and the occult. Nothing here resolves quickly, and most of it resolves eventually.",
        9: "Belief is tested before it holds. The father is distant, strict or absent. Fortune arrives late and is not withdrawn. Conservative by temperament.",
        10: "One of the strongest career placements. Authority through structure, endurance and time. Slow ascent, high ceiling, and standing that does not wobble.",
        11: "Large gains, late. Income compounds through persistence, the network is small and useful, and elder siblings are serious or absent.",
        12: "Expenditure, isolation and institutions. Foreign residence, hospitals, prisons, ashrams. Sleep is disturbed. In a spiritual chart this is the placement of the genuine renunciate.",
    },
    "Rahu": {
        1: "An unusual, magnetic and slightly foreign presence. Enormous drive attached to the self, an identity that is partly performance, and a life that does not follow the family pattern.",
        2: "Hunger for wealth and an unconventional relationship with speech: either extremely persuasive or extremely careless. Family of origin is complicated or foreign.",
        3: "Excellent placement. Ambition applied to effort. Bold, unconventional, technically able, and effective in media and communication.",
        4: "Unsettled foundations. Foreign home, complicated mother, property that is unusual or disputed. Peace of mind is the thing to work on.",
        5: "Unorthodox intelligence and a hunger around children and creativity. Speculation is a genuine trap here. Mantra practice needs a teacher.",
        6: "Excellent placement. Rahu devours enemies, debt and disease. Strong in litigation, competition and anything adversarial. Health anxiety is the cost.",
        7: "Unconventional or foreign partner. Marriage is intense, unusual, and often the site of the life's biggest illusion and biggest growth.",
        8: "Occult capacity, sudden events, and other people's money. Research aptitude is real. The chart's most unpredictable placement.",
        9: "Unorthodox belief. Either a foreign tradition adopted wholesale or an argument with the inherited one. The father is unusual or absent.",
        10: "Excellent placement. Enormous career ambition, unconventional profession, foreign or technological work, and visibility that arrives faster than the competence to hold it.",
        11: "The best house for Rahu. Very large gains, wide network, ambitions met on a scale that surprises. The hunger does not switch off when they are.",
        12: "Foreign residence, hidden expenditure, and either genuine spiritual reach or genuine escapism. Sleep and the subconscious are active. Substances are the standing risk.",
    },
    "Ketu": {
        1: "Detached from the body and from self-presentation. Self-doubt alongside real capability, an unusual mark or feature, and a life that does not organise around personal ambition.",
        2: "Detached from wealth and family. Speech is spare or cutting. Money comes and matters less than it should.",
        3: "Detachment applied to effort. Courage without ambition, few siblings or distance from them, and skill that is not marketed.",
        4: "Cut off from home nourishment. The mother is distant or the home was provisional. Deep inner life, weak outer comfort.",
        5: "Detached from children and creative output. Real intelligence with no wish to display it. The best placement for mantra and inner practice.",
        6: "Excellent placement. Enemies simply do not connect. Illness is diagnosed late but survives. Healing capacity, often unexplained.",
        7: "Detachment in partnership. Marriage is present and emotionally unavailable, or renounced. The classical placement for a spiritual partnership rather than a worldly one.",
        8: "The strongest placement for occult capacity. Sudden events, past-life depth, and genuine access to what is hidden. Longevity is usually good.",
        9: "Rejects the inherited tradition and finds an inner one. The father is absent or renunciate. Fortune is real but never pursued.",
        10: "Detached from career ambition despite ability. Work is done well and left behind. Public recognition arrives and is not enjoyed.",
        11: "Detached from gain and from networks. Income arrives, friendships are few, and desires do not accumulate.",
        12: "The strongest moksha placement in the chart. Natural renunciate, foreign residence, and a genuine capacity for release. Practically, expenditure that cannot be tracked.",
    },
}


def graha_in_sign(graha: str, sign: int) -> str:
    return GRAHA_IN_SIGN.get(graha, {}).get(sign % 12, "")


def graha_in_house(graha: str, house: int) -> str:
    return GRAHA_IN_HOUSE.get(graha, {}).get(house, "")


# ---------------------------------------------------------------------------
# Transit results, written for someone who does not read Sanskrit.
#
# Four fields per placement, because that is the order a person actually asks
# the questions in:
#   area  -- which part of life this lands on
#   what  -- what tends to happen there
#   watch -- where the difficulty shows up, and why it shows up there
#   helps -- what actually reduces the friction, stated as behaviour
#
# The slow grahas get full treatment because those are the transits that
# structure a year. The fast ones get a line each, because a three week Mercury
# transit does not deserve a paragraph.
# ---------------------------------------------------------------------------

# Roughly how long each graha spends in one sign, for phrasing durations.
TRANSIT_DURATION = {
    "Sun": "about a month", "Moon": "about two and a quarter days",
    "Mars": "about six weeks", "Mercury": "about three weeks",
    "Jupiter": "about a year", "Venus": "about a month",
    "Saturn": "about two and a half years",
    "Rahu": "about eighteen months", "Ketu": "about eighteen months",
}

SLOW = ("Saturn", "Jupiter", "Rahu", "Ketu")

TRANSIT_PHALA = {
    "Saturn": {
        1: {"area": "Your body, energy and sense of self",
            "what": "Energy drops and the body asks for less. This is the stretch where you stop being able to run on enthusiasm and have to run on structure instead. People often look older by the end of it and feel steadier.",
            "watch": "Tiredness that sleep does not fix, low mood, joints and bones, and a heavy sense that everything takes longer than it should. It bites here because Saturn is sitting on the house that governs vitality itself, so there is no part of life it does not slow.",
            "helps": "Sleep on a fixed schedule, eat at fixed times, and cut the number of commitments rather than trying to do them faster. Saturn rewards less done properly and punishes more done badly."},
        2: {"area": "Money, savings, family and how you speak",
            "what": "Income tightens or becomes irregular, and spending gets audited whether you want it audited or not. Family obligations show up as expenses. Speech becomes more careful.",
            "watch": "Debt accumulating quietly, arguments with family about money, and a habit of saying less than you mean until resentment builds. The friction is here because Saturn restricts whatever it touches, and this is the house of what you have put aside.",
            "helps": "Write down every outgoing for one month. Say the difficult thing early and plainly rather than storing it. Do not lend money you need back."},
        3: {"area": "Courage, siblings, short travel and daily communication",
            "what": "One of Saturn's better positions. Effort starts paying. Work that needed persistence rather than brilliance finally moves.",
            "watch": "Distance from siblings, and a flatness about taking initiative. The risk here is not disaster, it is not bothering.",
            "helps": "Pick the long project you have been avoiding and start it now. This transit is built for exactly that."},
        4: {"area": "Home, mother, property and peace of mind",
            "what": "The hardest Saturn transit for inner comfort. Home becomes a duty. Property matters drag. The mother's health or circumstances often need attention.",
            "watch": "Loneliness inside a full house, a low-grade unhappiness with no obvious cause, and chest or heart complaints. It lands hard because Saturn is a graha of separation sitting on the house of belonging.",
            "helps": "Do not make a permanent decision about where you live while this runs. Keep one room and one hour that are genuinely yours. Attend to the mother before it becomes urgent."},
        5: {"area": "Children, creativity, romance and speculation",
            "what": "Creative output slows and gets more serious. Matters concerning children need patience. Study becomes harder and deeper.",
            "watch": "Losses in speculation and trading, and a coldness entering a romance. Avoid the market during this one.",
            "helps": "Treat creative work as practice rather than performance. Give children structure rather than intensity."},
        6: {"area": "Work, health, debts and opposition",
            "what": "One of Saturn's three strong positions. You out-last people. Competitors fail, old debts get cleared, chronic health issues finally get diagnosed and managed.",
            "watch": "Overworking because it is working. The failure mode here is burnout disguised as productivity.",
            "helps": "Take on the fight or the workload you have been avoiding. Also take actual days off, because nothing external will force you to."},
        7: {"area": "Marriage, business partners and open dealings",
            "what": "Saturn is at full strength here but it tests the pair. Partnerships get formalised or get finished. Distance, obligation and silence enter the marriage.",
            "watch": "A partner who feels absent even when present, and business partnerships that quietly stop being fair. Saturn opposes the lagna from here, so pressure arrives through other people rather than from inside.",
            "helps": "Put agreements in writing, including domestic ones. Say what you need explicitly, once, in plain language. Do not wait for the other person to notice."},
        8: {"area": "Crisis, inheritance, joint money and the hidden",
            "what": "Slow-moving, uncomfortable, and usually productive in hindsight. Things that were structurally wrong surface and cannot be re-buried.",
            "watch": "Chronic health, joint finances, and inheritance disputes. Energy is low and interest in ordinary life is lower. It bites because two houses of difficulty are combined.",
            "helps": "Get the medical check and the financial audit done early rather than late. This transit punishes avoidance specifically."},
        9: {"area": "Luck, father, belief, law and long journeys",
            "what": "Fortune goes quiet. Things that used to come easily need paperwork. Belief gets examined rather than felt.",
            "watch": "The father's health, legal delays, and a loss of faith that reads as cynicism. Saturn restricts the house of grace, so the sense of being carried disappears.",
            "helps": "Do not start litigation during this. Rebuild belief through practice rather than through feeling, because the feeling will not arrive first."},
        10: {"area": "Career, authority and public standing",
            "what": "Saturn's strongest career transit and its most demanding. Responsibility increases before recognition does. Work that is genuinely yours consolidates. Work that was not falls away.",
            "watch": "Being handed the load without the title, and a boss or institution that becomes a real obstacle. The pressure is real because this is Saturn in its own house of karma.",
            "helps": "Deliver visibly and document it. Ask for the title once, formally, in writing. Do not resign in the first year of this transit."},
        11: {"area": "Income, gains, friends and elder siblings",
            "what": "The best Saturn transit for money. Income rises, though it arrives slowly and through work rather than luck. Older, more useful people enter the network.",
            "watch": "Friendships thinning out. Some of that is correct and some of it is neglect.",
            "helps": "Ask for the raise, apply for the bigger role, restructure the debt. This is the window."},
        12: {"area": "Expenses, sleep, foreign matters and letting go",
            "what": "Money goes out for reasons that are usually legitimate: medical, family, travel, education. Withdrawal from public life. Spiritual practice becomes genuinely effective.",
            "watch": "Insomnia, isolation, hospital visits and a general sense of expenditure without return. This also opens the next Sade Sati.",
            "helps": "Cut discretionary spending now, before the next two and a half years. Start the practice you have been meaning to start; this transit actually supports it."},
    },
    "Jupiter": {
        1: {"area": "Yourself, health and how you are seen",
            "what": "Confidence returns. Weight often returns with it. People take you more seriously and opportunities arrive without being chased.",
            "watch": "Over-commitment and over-expansion. Jupiter enlarges everything including bad judgement and the waistline.",
            "helps": "Say yes to one big thing, not four. Use the goodwill on something structural."},
        2: {"area": "Money, savings, family and speech",
            "what": "A genuinely good year for income and family. Savings grow, family expands or reconciles, and your word carries further than usual.",
            "watch": "Spending in proportion to the increase, so nothing is left at the end.",
            "helps": "Move a fixed percentage into savings automatically before it can be spent."},
        3: {"area": "Effort, siblings, communication and short travel",
            "what": "Mixed. Jupiter is not comfortable in a house of self-effort. Communication and publishing do well; personal drive dips.",
            "watch": "Complacency. Things go well enough that the harder work gets postponed.",
            "helps": "Set deadlines externally, since the internal pressure will not appear."},
        4: {"area": "Home, mother, property and inner peace",
            "what": "One of the best transits in the cycle. Property, vehicles, domestic happiness, and the mother's wellbeing. Real contentment, not just good luck.",
            "watch": "Very little. If you are buying property, this is the window.",
            "helps": "Make the domestic decision you have been deferring."},
        5: {"area": "Children, creativity, learning and romance",
            "what": "Excellent. Conception, creative output, education and romance all favoured. Advice you give lands well.",
            "watch": "Speculation feels safe and mostly is not, even here.",
            "helps": "Start the course, the book or the family. This transit backs all three."},
        6: {"area": "Work, health, debts and opposition",
            "what": "Difficult, and one of Jupiter's three weak positions. Expansion in a house of loss expands the loss.",
            "watch": "Weight, liver and blood sugar; debts taken on optimistically; and enemies who are better resourced than you assumed.",
            "helps": "Get the annual bloodwork. Do not consolidate debt into a bigger loan on the assumption that things will improve."},
        7: {"area": "Marriage, partnerships and public dealings",
            "what": "Excellent. The classical marriage transit. Existing partnerships improve, new ones form, business partners appear.",
            "watch": "Agreeing to a partnership on optimism rather than terms.",
            "helps": "If you are going to marry or sign, this is the year. Still read the contract."},
        8: {"area": "Crisis, inheritance, joint finances and the hidden",
            "what": "Another weak position, though it protects. Inheritance and joint money feature. Occult and psychological work goes deep.",
            "watch": "Sudden expenses, and a tendency to be optimistic about other people's money.",
            "helps": "Insure things. Read the small print on anything jointly held."},
        9: {"area": "Fortune, father, belief, law and long journeys",
            "what": "Jupiter in its own natural house. The strongest transit for luck, teaching, travel, law and higher study. Things resolve in your favour.",
            "watch": "Assuming it will last. It runs a year.",
            "helps": "Start the long journey, the degree, the case or the teaching now."},
        10: {"area": "Career, authority and reputation",
            "what": "Mixed, and often misread. Jupiter here dilutes ambition rather than fuelling it. Reputation improves; drive does not.",
            "watch": "Coasting on goodwill and missing a window that needed push.",
            "helps": "Set concrete career targets with dates, because the ambient ease will not supply them."},
        11: {"area": "Income, gains, friends and ambitions",
            "what": "The single best transit for money and network. Gains arrive from several directions at once and ambitions get met.",
            "watch": "Gains being spent as fast as they land, and a network that grows wide and shallow.",
            "helps": "Bank a fixed share of every windfall. Keep the five relationships that actually matter."},
        12: {"area": "Expenses, foreign matters, retreat and release",
            "what": "Spending on good things: travel, teachers, education, charity, health. Genuine spiritual progress. Foreign matters open.",
            "watch": "Money leaving faster than it arrives, and generosity that is not affordable.",
            "helps": "Budget for the giving rather than discovering it afterwards. Take the retreat; it works this year."},
    },
    "Rahu": {
        1: {"area": "Identity, body and how you present",
            "what": "A reinvention of the self, often visible: appearance, name, city, field. Ambition attaches to the person directly.",
            "watch": "Becoming a persona rather than a person, and health complaints that no test explains.",
            "helps": "Keep two or three people around who knew you before this started and will say so."},
        2: {"area": "Money, family and speech",
            "what": "Sudden increases in income and equally sudden appetite for more. Family matters get complicated or foreign.",
            "watch": "Money made in ways that are hard to explain, and speech that overpromises.",
            "helps": "Keep the accounting clean and boring. Say only what you can deliver."},
        3: {"area": "Courage, communication, siblings and short travel",
            "what": "Strong placement. Bold, unconventional action pays. Media, technology and communication all favoured.",
            "watch": "Recklessness that works often enough to become a habit.",
            "helps": "Take the calculated risk, not the uncalculated one. Write the plan down first."},
        4: {"area": "Home, mother and peace of mind",
            "what": "Unsettled. Relocation, often foreign. Property matters become unusual or disputed. The mother's situation changes.",
            "watch": "Restlessness at home, disturbed sleep, and a sense of not belonging anywhere. This is where Rahu is least comfortable.",
            "helps": "Build one fixed daily routine and hold it wherever you are living. Do not move twice."},
        5: {"area": "Children, creativity, romance and speculation",
            "what": "Unorthodox creative output and intense romance. Matters around children become significant.",
            "watch": "Speculation, gambling and crypto. This is the single most dangerous transit for that, and it will feel like insight.",
            "helps": "Put a hard cap on any speculative position before opening it. Take advice from someone with no stake."},
        6: {"area": "Work, health, debts and opposition",
            "what": "One of Rahu's best positions. Enemies are outmanoeuvred, competition is won, debts are managed aggressively.",
            "watch": "Health anxiety, and winning fights that were not worth having.",
            "helps": "Pick the fights deliberately. Use the aggression on the work rather than on people."},
        7: {"area": "Marriage, partnerships and the public",
            "what": "Intense. Unconventional or foreign partners. Existing marriages get tested by an outside factor.",
            "watch": "Infatuation mistaken for compatibility, and business partners who are not what they present as.",
            "helps": "Verify claims independently. Do not sign or marry in the first six months of this transit."},
        8: {"area": "Crisis, joint money, inheritance and the hidden",
            "what": "The most volatile placement. Sudden events, research breakthroughs, and other people's money moving.",
            "watch": "Debt, insurance, tax and inheritance disputes, plus obsessive interest in occult material.",
            "helps": "Keep financial records complete. Do not take on jointly liable debt."},
        9: {"area": "Belief, father, law and long journeys",
            "what": "Belief is overhauled, often by adopting a foreign or unorthodox tradition. Foreign travel opens up.",
            "watch": "Guru fixation, and adopting a whole system on someone else's authority.",
            "helps": "Keep asking questions after you have committed. A teacher who discourages that is the wrong teacher."},
        10: {"area": "Career, status and public visibility",
            "what": "Strong. Big career moves, unconventional or technological work, foreign employers, rapid visibility.",
            "watch": "Rising faster than competence, and reputation built on presentation rather than delivery.",
            "helps": "Take the role and then close the skill gap fast and privately."},
        11: {"area": "Income, gains, network and ambitions",
            "what": "Rahu's best house. Very large gains, wide network, ambitions met on an unexpected scale.",
            "watch": "The appetite not switching off, and a circle full of people who want something.",
            "helps": "Define what enough looks like now, in writing, while it is still theoretical."},
        12: {"area": "Expenses, foreign residence, sleep and the subconscious",
            "what": "Foreign matters open. Hidden expenditure. Genuine spiritual reach for some, and drift for others.",
            "watch": "Substances, insomnia, hidden losses, and enemies you cannot see. The most escapist placement.",
            "helps": "Track spending weekly. Keep alcohol and substances out of it entirely during this transit."},
    },
    "Ketu": {
        1: {"area": "Identity, body and self-confidence",
            "what": "Detachment from your own image. Interest in how you are perceived drops away, which is freeing and disorienting at once.",
            "watch": "Self-doubt that does not match your actual ability, and vague health complaints.",
            "helps": "Judge yourself on output rather than on feeling. The feeling is unreliable this year."},
        2: {"area": "Money, family and speech",
            "what": "Detachment from accumulation. Money matters less. Family ties loosen without a quarrel.",
            "watch": "Neglecting finances because they have stopped feeling important.",
            "helps": "Automate the saving so that indifference does not cost you."},
        3: {"area": "Courage, siblings and communication",
            "what": "Effort continues without appetite. Skill is present, ambition is not. Distance from siblings.",
            "watch": "Abandoning things at eighty percent because the interest ran out.",
            "helps": "Commit externally, so someone else is expecting the finished thing."},
        4: {"area": "Home, mother and inner peace",
            "what": "Detachment from home. The house stops feeling like home, or you leave it.",
            "watch": "Emotional withdrawal from the mother and from the family, and a flat unhappiness at home.",
            "helps": "Stay in contact even when you do not feel like it. The feeling returns later; the relationship may not."},
        5: {"area": "Children, creativity and study",
            "what": "The best placement for inner practice. Mantra, meditation and deep study go unusually well.",
            "watch": "Distance from children, and creative work abandoned as pointless.",
            "helps": "Use it for practice rather than production. That is what it is for."},
        6: {"area": "Work, health, debts and opposition",
            "what": "Strong. Opposition simply fails to connect. Old debts and old illnesses resolve, sometimes without explanation.",
            "watch": "Symptoms that are dismissed too easily, since the interest in the body is low.",
            "helps": "Keep the routine medical checks even though nothing feels wrong."},
        7: {"area": "Marriage and partnerships",
            "what": "Detachment inside the relationship. Present but unavailable, on one side or both.",
            "watch": "A marriage going quiet rather than going wrong, which is harder to notice and harder to repair.",
            "helps": "Schedule the time rather than waiting for the desire. Say the unglamorous thing out loud."},
        8: {"area": "Crisis, the occult and joint finances",
            "what": "The strongest placement for occult and psychological depth. Real insight arrives unbidden.",
            "watch": "Sudden events, and disinterest in joint financial matters that need attention.",
            "helps": "Do the inner work, and delegate the paperwork to someone who cares about it."},
        9: {"area": "Belief, father and long journeys",
            "what": "The inherited tradition stops fitting. An inner authority replaces the outer one.",
            "watch": "Rejecting good guidance along with the bad, and distance from the father.",
            "helps": "Leave one door open. You will want a teacher again in about two years."},
        10: {"area": "Career and public standing",
            "what": "Competence without ambition. The work is done well and the promotion is not chased.",
            "watch": "Drifting out of a career by neglect rather than by decision.",
            "helps": "Make the career decision deliberately, even if the decision is to stay put."},
        11: {"area": "Income, gains and network",
            "what": "Detachment from gain. Income continues, the hunger does not. The circle thins.",
            "watch": "Letting useful relationships lapse, and undercharging because it stopped mattering.",
            "helps": "Keep the professional relationships warm with minimal effort. Review your rates once."},
        12: {"area": "Expenses, retreat and release",
            "what": "The strongest transit for genuine spiritual practice and for letting things go.",
            "watch": "Expenditure that cannot be accounted for, and withdrawal that tips into isolation.",
            "helps": "Take the retreat. Also tell two people where you are."},
    },
    "Mars": {
        1: {"area": "Body and drive", "what": "Energy, impatience and physical push.", "watch": "Accidents, inflammation, and picking fights.", "helps": "Train hard, argue less."},
        2: {"area": "Money and speech", "what": "Aggressive earning and sharp words.", "watch": "Saying the cutting thing to family.", "helps": "Wait a day before sending it."},
        3: {"area": "Courage and effort", "what": "Excellent. Initiative pays.", "watch": "Friction with siblings.", "helps": "Start the hard thing now."},
        4: {"area": "Home and property", "what": "Domestic friction, property activity.", "watch": "Arguments at home, and haste over land.", "helps": "Handle the property paperwork slowly."},
        5: {"area": "Children and speculation", "what": "Competitive intelligence.", "watch": "Losses in trading, and heat with children.", "helps": "No leveraged positions this month."},
        6: {"area": "Work and conflict", "what": "Strong. You win contested things.", "watch": "Injury and overexertion.", "helps": "Take the fight, warm up first."},
        7: {"area": "Marriage and partners", "what": "Heat in the partnership.", "watch": "Arguments escalating faster than usual.", "helps": "Take the disagreement outside the house."},
        8: {"area": "Crisis and joint money", "what": "Sudden events and expenses.", "watch": "Accidents, surgery, and rash financial moves.", "helps": "Drive carefully; delay the big transaction."},
        9: {"area": "Belief and travel", "what": "Energetic long travel, forceful convictions.", "watch": "Conflict with the father or a teacher.", "helps": "Argue the principle, not the person."},
        10: {"area": "Career", "what": "Strong. Decisive professional action.", "watch": "Clashing with authority.", "helps": "Use the drive on the work, not the boss."},
        11: {"area": "Income and network", "what": "Gains through push and competition.", "watch": "Friction with elder siblings or friends.", "helps": "Ask directly for what you want."},
        12: {"area": "Expenses and hidden matters", "what": "Energy drains, hidden opposition.", "watch": "Fatigue, hidden enemies, sudden costs.", "helps": "Rest properly and keep your plans quiet."},
    },
    "Sun": {
        1: {"area": "Self and vitality", "what": "Visibility and confidence rise.", "watch": "Ego friction and headaches.", "helps": "Lead, but let others speak."},
        2: {"area": "Money and family", "what": "Focus on income and family standing.", "watch": "Pride in family disputes.", "helps": "Concede the small point."},
        3: {"area": "Effort and siblings", "what": "Good for initiative and short travel.", "watch": "Dominating siblings.", "helps": "Push your own work forward."},
        4: {"area": "Home and mother", "what": "Attention turns home.", "watch": "Restlessness and chest complaints.", "helps": "Do the home task you have deferred."},
        5: {"area": "Children and creativity", "what": "Creative and advisory work is favoured.", "watch": "Speculation losses.", "helps": "Publish or present something."},
        6: {"area": "Work and health", "what": "Strong. You beat competition.", "watch": "Digestive complaints.", "helps": "Confront the work problem directly."},
        7: {"area": "Partnership", "what": "Partner matters take centre stage.", "watch": "Ego clashes in the marriage.", "helps": "Ask rather than assert."},
        8: {"area": "Crisis and the hidden", "what": "Low energy, hidden matters surface.", "watch": "Vitality dips and old issues return.", "helps": "Rest and deal with the buried thing."},
        9: {"area": "Fortune and father", "what": "Good for travel, law and teaching.", "watch": "Dogmatism.", "helps": "Make the long-term plan now."},
        10: {"area": "Career", "what": "The best solar month. Visibility and authority.", "watch": "Overreaching publicly.", "helps": "Ask for the thing you want at work."},
        11: {"area": "Income and network", "what": "Gains and useful introductions.", "watch": "Friction with elder siblings.", "helps": "Follow up on the introduction."},
        12: {"area": "Expenses and retreat", "what": "Low visibility, higher spending.", "watch": "Fatigue and eye strain.", "helps": "Plan rather than launch this month."},
    },
    "Venus": {
        1: {"area": "Self and appearance", "what": "Charm and ease.", "watch": "Indulgence.", "helps": "Good month for anything social."},
        2: {"area": "Money and speech", "what": "Income and pleasant speech.", "watch": "Spending on comfort.", "helps": "Negotiate now."},
        3: {"area": "Communication", "what": "Artistic and social effort pays.", "watch": "Laziness.", "helps": "Pitch the creative idea."},
        4: {"area": "Home", "what": "Domestic comfort and beautification.", "watch": "Overspending on the home.", "helps": "Host something."},
        5: {"area": "Romance and creativity", "what": "The best Venus month. Romance and art.", "watch": "Speculation dressed as intuition.", "helps": "Start the creative project."},
        6: {"area": "Work and health", "what": "Weak. Pleasure entangled with obligation.", "watch": "Relationship strain through work, and kidney or reproductive complaints.", "helps": "Protect one evening a week."},
        7: {"area": "Partnership", "what": "Excellent for marriage and agreements.", "watch": "Agreeing too easily.", "helps": "Good month to marry or to sign."},
        8: {"area": "Joint finances and intimacy", "what": "Intense attachments, gains through the partner.", "watch": "Secrecy in relationships.", "helps": "Say the thing you are not saying."},
        9: {"area": "Travel and belief", "what": "Pleasant travel, foreign connections.", "watch": "Extravagance abroad.", "helps": "Book the trip."},
        10: {"area": "Career", "what": "Public likeability, good for client work.", "watch": "Coasting on charm.", "helps": "Meet the clients in person."},
        11: {"area": "Gains and network", "what": "Gains through people and art.", "watch": "A wide, shallow circle.", "helps": "Ask the network for what you need."},
        12: {"area": "Expenses and private life", "what": "Private pleasures, foreign matters, expenditure.", "watch": "Hidden spending and secret attachments.", "helps": "Take the holiday; keep the budget."},
    },
    "Mercury": {
        1: {"area": "Mind and speech", "what": "Quick thinking and good communication.", "watch": "Restlessness and overthinking.", "helps": "Write it down; decide once."},
        2: {"area": "Money and speech", "what": "Good for negotiation and trade.", "watch": "Talking past the close.", "helps": "Make the financial call."},
        3: {"area": "Communication", "what": "Strong. Writing, media, short travel.", "watch": "Scattered attention.", "helps": "Ship the piece of writing."},
        4: {"area": "Home and study", "what": "Good for study and domestic admin.", "watch": "Mental restlessness at home.", "helps": "Clear the paperwork backlog."},
        5: {"area": "Learning and creativity", "what": "Excellent for study and analysis.", "watch": "Overanalysing a romance.", "helps": "Sit the exam, take the course."},
        6: {"area": "Work and health", "what": "Strong for problem solving and admin.", "watch": "Nerves, skin, and worry loops.", "helps": "Break the work into written steps."},
        7: {"area": "Partnership and contracts", "what": "Good for agreements and discussion.", "watch": "Winning the argument, losing the point.", "helps": "Get the terms in writing."},
        8: {"area": "Research and joint money", "what": "Good for research and investigation.", "watch": "Suspicion, and fiddly tax or insurance matters.", "helps": "Do the deep-dive research now."},
        9: {"area": "Learning and travel", "what": "Good for higher study, publishing and law.", "watch": "Missing the detail in a big plan.", "helps": "Read the contract properly."},
        10: {"area": "Career", "what": "Strong. Communication-led career progress.", "watch": "Promising delivery dates too fast.", "helps": "Present, pitch, interview."},
        11: {"area": "Network and income", "what": "Gains through information and contacts.", "watch": "Too many conversations, too few decisions.", "helps": "Convert two conversations into commitments."},
        12: {"area": "Private work and expenses", "what": "Good for research, writing and planning alone.", "watch": "Overthinking at night, disturbed sleep.", "helps": "Work early, stop late-night thinking."},
    },
    "Moon": {
        1: {"area": "Mood and self", "what": "Feelings are close to the surface.", "watch": "Reacting from mood.", "helps": "Decide nothing important today."},
        2: {"area": "Money and family", "what": "Warm family contact.", "watch": "Comfort spending.", "helps": "Call the family."},
        3: {"area": "Communication", "what": "Good for conversation and short trips.", "watch": "Restlessness.", "helps": "Have the conversation."},
        4: {"area": "Home", "what": "The Moon's best position. Comfort and rest.", "watch": "Not wanting to leave the house.", "helps": "Rest properly today."},
        5: {"area": "Creativity and romance", "what": "Emotionally creative and romantic.", "watch": "Sentimentality.", "helps": "Make something."},
        6: {"area": "Work and health", "what": "Emotionally taxing work days.", "watch": "Anxiety and digestion.", "helps": "Keep the day structured."},
        7: {"area": "Partnership", "what": "Emotional focus on the partner.", "watch": "Neediness.", "helps": "Spend the evening together."},
        8: {"area": "Hidden matters", "what": "Emotionally heavy and inward.", "watch": "Old feelings surfacing.", "helps": "Let it pass; do not act on it."},
        9: {"area": "Belief and travel", "what": "Optimistic and expansive mood.", "watch": "Overpromising.", "helps": "Plan the trip."},
        10: {"area": "Career", "what": "Publicly visible, emotionally driven work.", "watch": "Mood leaking into professional settings.", "helps": "Do the client-facing work."},
        11: {"area": "Friends and gains", "what": "Social and well-connected days.", "watch": "Emotional spending in company.", "helps": "See friends."},
        12: {"area": "Rest and retreat", "what": "Withdrawn, tired, inward.", "watch": "Low mood and poor sleep.", "helps": "Take the quiet day. Do not schedule anything."},
    },
}


def transit_phala(graha: str, house: int) -> dict:
    return TRANSIT_PHALA.get(graha, {}).get(house, {})
